# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-24 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_add', models.CharField(max_length=500)),
                ('destination_add', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=1000)),
                ('intersection', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_name', models.CharField(max_length=500)),
                ('lat', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('lon', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('street_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Route')),
            ],
        ),
    ]
